/**
 * Three curated example texts for the Brain Mirror room. Each demonstrates
 * a different brain pattern; the activations here are precomputed by the
 * same fakePredictor logic so the previews stay coherent with what users
 * see when they type. When Phase 10 wires real TRIBE inference, these can
 * be regenerated by feeding the same texts through the real model.
 */

import { fakePredict } from "./fakePredictor";
import type { RegionId } from "./regions";

export type SavedExample = {
  id: string;
  label: string;
  attribution: string;
  body: string;
  framing: string;
  activations: Partial<Record<RegionId, number>>;
};

const examples: Omit<SavedExample, "activations">[] = [
  {
    id: "the-grief-list",
    label: "The Grief List",
    attribution: "after Anne Carson",
    body:
      "There is a list of things she has not done since you left: " +
      "boiled water, walked past the bakery, opened the back drawer. " +
      "She keeps the list because she is afraid that to forget it would " +
      "be to forget what the absence costs.",
    framing:
      "Concrete nouns and emotional vocabulary together. The fake predictor " +
      "warms the hippocampus, amygdala, and ATL — the memory of bodies and " +
      "rooms, and the salience of what's missing.",
  },
  {
    id: "the-borges-thought",
    label: "The Borges Thought",
    attribution: "after Borges",
    body:
      "Time is a river that carries me, but I am the river. " +
      "It is a tiger that devours me, but I am the tiger. " +
      "It is a fire that consumes me, but I am the fire. " +
      "The world, unfortunately, is real. I, unfortunately, am Borges.",
    framing:
      "Abstract self-reference layered with questions of identity. The " +
      "default-mode network and angular gyrus — language meeting the self " +
      "thinking about itself — read as the strongest signal here.",
  },
  {
    id: "the-thai-lullaby-line",
    label: "A line from a Thai lullaby",
    attribution: "บทกล่อมเด็ก, traditional",
    body:
      "Sleep now, little one, while the moon is round and the rain has " +
      "forgotten its way home. The kitchen is dark and the cricket has " +
      "remembered its song.",
    framing:
      "Music-adjacent vocabulary (song, rhythm of the line) plus concrete " +
      "domestic imagery. Heschl's gyrus and the right posterior STG light, " +
      "and the hippocampus carries the scene.",
  },
];

export const savedExamples: SavedExample[] = examples.map((ex) => ({
  ...ex,
  activations: fakePredict(ex.body).activations,
}));
